// Pull Unbounded and Lexend into the repo so the dashboard doesn't depend on
// Google's servers at page load. Self-hosting is faster (no second DNS lookup
// and connection), private (no request to Google every time you open it), and
// it keeps working if a CDN changes its URLs.
//
// Run once via the "Fetch fonts" workflow; re-run only to add weights.

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(new URL('..', import.meta.url).pathname);
const OUT = path.join(ROOT, 'fonts');

// A modern browser UA is what makes Google return woff2 rather than legacy ttf.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const FAMILIES = [
  { name: 'Unbounded', weights: [400, 600, 800] },
  { name: 'Lexend',    weights: [300, 400, 500] },
];

fs.mkdirSync(OUT, { recursive: true });
let css = '/* Self-hosted. Generated by scripts/fetch-fonts.mjs — do not hand-edit. */\n';

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.name}:wght@${fam.weights.join(';')}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${fam.name}: Google returned ${res.status}`);
  const sheet = await res.text();

  // Each @font-face block carries its own unicode-range; keep only latin so we
  // aren't shipping Cyrillic and Vietnamese nobody will render.
  const blocks = sheet.split('@font-face').slice(1);
  let kept = 0;

  for (const block of blocks) {
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const src = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';
    if (!weight || !src) continue;
    // latin block is the one containing U+0000-00FF
    if (!/U\+0000-00FF/i.test(range)) continue;

    const file = `${fam.name.toLowerCase()}-${weight}.woff2`;
    const bin = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT, file), bin);
    kept++;

    css += `@font-face{font-family:'${fam.name}';font-style:normal;font-weight:${weight};` +
           `font-display:swap;src:url('${file}') format('woff2');unicode-range:${range.trim()};}\n`;
    console.log(`${file}  ${(bin.length / 1024).toFixed(1)} KB`);
  }
  if (!kept) throw new Error(`${fam.name}: no latin faces found — Google changed its response`);
}

fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
console.log(`\nWrote fonts/fonts.css with ${css.split('@font-face').length - 1} faces.`);
